web:
  build: .
  environment:
    DATABASE_URL: ecto://phoenixdocker:phoenixdocker@db/phoenixdocker_prod
    PORT: 4001
  links:
    - db
  ports:
    - 4001:4001
db:
  image: postgres:9.4
  environment:
    POSTGRES_USER: phoenixdocker
    POSTGRES_PASSWORD: phoenixdocker
